flask_app/models.py
import hashlib
import enum
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app, request
from flask_login import UserMixin, AnonymousUserMixin
from . import login_manager
from datetime import datetime
from markdown import markdown
import bleach


# class StatusTask:
#     status = {
#     'development': DevelopmentConfig,
#     'testing': TestingConfig,
#     'production': ProductionConfig,
#
#     'default': DevelopmentConfig
# }
class Status(db.Model):
    __tables__ = 'status'
    STATUS_LIST = ['new', 'in work', 'executed', 'closed', 'cancelled']
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32), index=True)
    tasks = db.relationship('Task', backref='status', lazy='dynamic')

    def __repr__(self):
        return self.name


class Task(db.Model):
    __tables__ = 'tasks'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(128), index=True)
    body = db.Column(db.Text)
    date_created = db.Column(db.DateTime, default=datetime.utcnow)
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    done = db.Column(db.Boolean, default=False, index=True)
    title_html = db.Column(db.Text)
    comments = db.relationship('Comment', backref='task', lazy='dynamic')
    status_id = db.Column(db.Integer, db.ForeignKey('status.id'))


    def __init__(self, **kwargs):
        super(Task, self).__init__(**kwargs)
        if self.status_id is None:
            self.status = Status.query.filter_by(name='new').first()

    @staticmethod
    def on_changed_title(target, value, oldvalue, initiator):
        allowed_tags = ['a', 'abbr', 'acronym', 'b', 'blockquote', 'code',
                        'em', 'i', 'li', 'ol', 'pre', 'strong', 'ul',
                        'h1', 'h2', 'h3', 'p']

        target.body_html = bleach.linkify(bleach.clean(
            markdown(value, output_format='html'),
            tags=allowed_tags, strip=True))



    # def change_status(self, token):
    #
    #     s = Serializer(current_app.config['SECRET_KEY'])
    #     try:
    #         data = s.loads(token.encode('utf-8'))
    #     except:
    #         return False
    #     if data.get('change_status') != self.id:
    #         return False
    #     new_status = data.get('new_status')
    #     if new_status is None:
    #         return False


        # s_closed = TaskStatus.query.filter_by(name='closed').first()
        # if new_status == s_closed:
        #     self.done = True
        #
        # self.status = new_status
        #
        #
        # db.session.add(self)
        # return True





db.event.listen(Task.title, 'set', Task.on_changed_title)


class Permission:
    FOLLOW = 1
    COMMENT = 2
    WRITE = 4
    MODERATE = 8
    ADMIN = 16


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    default = db.Column(db.Boolean, default=False, index=True)
    permissions = db.Column(db.Integer, default=16)
    users = db.relationship('User', backref='role', lazy='dynamic')

    def __init__(self, **kwargs):
        super(Role, self).__init__(**kwargs)
        if self.permissions is None:
            self.permissions = 0

    # @staticmethod
    # def insert_roles():
    #     roles = {
    #         'User': [Permission.FOLLOW, Permission.COMMENT, Permission.WRITE],
    #         'Moderator': [Permission.FOLLOW, Permission.COMMENT,
    #                       Permission.WRITE, Permission.MODERATE],
    #         'Administrator': [Permission.FOLLOW, Permission.COMMENT,
    #                           Permission.WRITE, Permission.MODERATE,
    #                           Permission.ADMIN],
    #     }
    #     default_role = 'User'
    #     for r in roles:
    #         role = Role.query.filter_by(name=r).first()
    #         if role is None:
    #             role = Role(name=r)
    #         role.reset_permissions()
    #         for perm in roles[r]:
    #             role.add_permission(perm)
    #         role.default = (role.name == default_role)
    #         db.session.add(role)
    #     db.session.commit()
    #
    # def add_permission(self, perm):
    #     if not self.has_permission(perm):
    #         self.permissions += perm
    #
    # def remove_permission(self, perm):
    #     if self.has_permission(perm):
    #         self.permissions -= perm
    #
    # def reset_permissions(self):
    #     self.permissions = 0
    #
    # def has_permission(self, perm):
    #     return self.permissions & perm == perm

    def __repr__(self):
        return f'Role {self.name}'


class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key=True)
    task_id = db.Column(db.Integer, db.ForeignKey('task.id'))
    commentator_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    body = db.Column(db.Text)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)

    def __init__(self, **kwargs):
        super(Comment, self).__init__(**kwargs)


class User(db.Model, UserMixin):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(64), unique=True, index=True)
    username = db.Column(db.String(64), unique=True, index=True)
    password_hash = db.Column(db.String(128))
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))
    confirmed = db.Column(db.Boolean, default=True)
    name = db.Column(db.String(64))
    location = db.Column(db.String(64))
    about_me = db.Column(db.Text())
    member_since = db.Column(db.DateTime(), default=datetime.utcnow)
    last_seen = db.Column(db.DateTime(), default=datetime.utcnow)
    avatar_hash = db.Column(db.String(32))
    tasks = db.relationship('Task', backref='author', lazy='dynamic')
    comments = db.relationship('Comment', backref='commentator', lazy='dynamic')


    def __init__(self, **kwargs):
        super(User, self).__init__(**kwargs)
        if self.role is None:
            if self.email == current_app.config['FLASKY_ADMIN']:
                self.role = Role.query.filter_by(name='Administrator').first()
            if self.role is None:
                self.role = Role.query.filter_by(default=True).first()
            if self.email is not None and self.avatar_hash is None:
                self.avatar_hash = self.gravatar_hash()

    @property
    def password(self):
        raise AttributeError('password is not a readable attribute')

    @password.setter
    def password(self, _password):
        self.password_hash = generate_password_hash(_password)

    def verify_password(self, _password):
        return check_password_hash(self.password_hash, _password)

    def generate_confirmation_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'confirm': self.id}).decode('utf-8')

    def confirm(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token.encode('utf-8'))
        except:
            return False
        if data.get('confirm') != self.id:
            return False
        self.confirmed = True
        db.session.add(self)
        return True

    def generate_reset_token(self, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps({'reset': self.id}).decode('utf-8')

    @staticmethod
    def reset_password(token, new_password):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token.encode('utf-8'))
        except:
            return False
        user = User.query.get(data.get('reset'))
        if user is None:
            return False
        user.password = new_password
        db.session.add(user)
        return True

    def generate_email_change_token(self, new_email, expiration=3600):
        s = Serializer(current_app.config['SECRET_KEY'], expiration)
        return s.dumps(
            {'change_email': self.id, 'new_email': new_email}).decode('utf-8')

    def change_email(self, token):
        s = Serializer(current_app.config['SECRET_KEY'])
        try:
            data = s.loads(token.encode('utf-8'))
        except:
            return False
        if data.get('change_email') != self.id:
            return False
        new_email = data.get('new_email')
        if new_email is None:
            return False
        if self.query.filter_by(email=new_email).first() is not None:
            return False
        self.email = new_email
        db.session.add(self)
        return True

    def ping(self):
        self.last_seen = datetime.utcnow()
        db.session.add(self)
        db.session.commit()

    # def can(self, perm):
    #     return self.role is not None and self.role.has_permission(perm)
    #
    # def is_administrator(self):
    #     return self.can(Permission.ADMIN)

    def gravatar_hash(self):
        return hashlib.md5(self.email.lower().encode('utf-8')).hexdigest()

    def gravatar(self, size=100, default='identicon', rating='g'):
        if request.is_secure:
            url = 'https://secure.gravatar.com/avatar'
        else:
            url = 'http://www.gravatar.com/avatar'
        hash = self.avatar_hash or self.gravatar_hash()
        return '{url}/{hash}?s={size}&d={default}&r={rating}'.format(
            url=url, hash=hash, size=size, default=default, rating=rating)

    def __repr__(self):
        return f'User {self.username}'


class AnonymousUser(AnonymousUserMixin):
    # def can(self, permission):
    #     return False
    #
    # def is_administrator(self):
    #     return False
    pass


# login_manager.anonymous_user = AnonymousUser

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

flask_app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length
from flask_pagedown.fields import PageDownField
from wtforms_sqlalchemy.fields import QuerySelectField
from ..models import Status


class NameForm(FlaskForm):
    name = StringField('What is your name?', validators=[DataRequired()])
    submit = SubmitField('Submit')


class TaskForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    body = TextAreaField("Body", validators=[DataRequired()])
    # status = SelectField('New status', coerce=int)
    submit = SubmitField('Submit')


class TaskCommentForm(FlaskForm):
    status = SelectField('New status', coerce=int)
    body = TextAreaField("Comment")
    submit = SubmitField('Save')


class EditProfileForm(FlaskForm):
    name = StringField('Real name', validators=[Length(0, 64)])
    location = StringField('Location', validators=[Length(0, 64)])
    about_me = TextAreaField('About me')
    submit = SubmitField('Submit')

flask_app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager
from flask_pagedown import PageDown

bootstrap = Bootstrap()
mail = Mail()
moment = Moment()
db = SQLAlchemy()


login_manager = LoginManager()
login_manager.login_view = 'auth.login'
pagedown = PageDown()


def create_app(config_name):
    app = Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)

    bootstrap.init_app(app)
    mail.init_app(app)
    moment.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)

    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')



    return app

flask_app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors
# from ..models import Permission

# @main.app_context_processor
# def inject_permissions():
#     return dict(Permission=Permission)

flask_app/main/views.py
from datetime import datetime
from flask import render_template, session, redirect, url_for, \
    abort, flash, request, current_app
from flask_login import login_required, current_user
from . import main
from .forms import NameForm, TaskForm, EditProfileForm, TaskCommentForm
from .. import db
from ..models import User, Role, Task, Comment, Status


# from ..decorators import admin_required

@main.route('/', methods=['GET', 'POST'])
def index():
    form = TaskForm()
    if form.validate_on_submit():
        task = Task(title=form.title.data, body=form.body.data,
                    author=current_user._get_current_object())
        db.session.add(task)
        db.session.commit()
        return redirect(url_for('.index'))

    page = request.args.get('page', 1, type=int)
    pagination = Task.query.order_by(Task.date_created.desc()).paginate(
        page, per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],
        error_out=False)
    tasks = pagination.items
    return render_template('index.html', form=form, tasks=tasks,
                           pagination=pagination)


@main.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first_or_404()
    tasks = user.tasks.order_by(Task.date_created.desc()).all()
    return render_template('user.html', user=user, tasks=tasks)


@main.route('/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.location = form.location.data
        current_user.about_me = form.about_me.data
        db.session.add(current_user._get_current_object())
        db.session.commit()
        flash('Your profile has been updated.')
        return redirect(url_for('.user', username=current_user.username))
    form.name.data = current_user.name
    form.location.data = current_user.location
    form.about_me.data = current_user.about_me
    return render_template('edit_profile.html', form=form)


@main.route('/task/<int:id>', methods=['GET', 'POST'])
def task(id):
    task = Task.query.get_or_404(id)
    comments = Comment.query.filter_by(task=task).all()
    n_comments = Comment.query.filter_by(task=task).count()
    form = TaskCommentForm()

    form.status.choices = [(row.id, row.name) for row in Status.query.all()]

    if form.validate_on_submit():
        new_status_id = form.status.data

        if new_status_id != task.status_id:
            task.status_id = new_status_id

            close_sts = Status.query.filter_by(name='closed').first()
            cancell_sts = Status.query.filter_by(name='cancelled').first()
            if close_sts is not None:
                if new_status_id == close_sts.id:
                    task.done = True
            if cancell_sts is not None:
                if new_status_id == cancell_sts.id:
                    task.done = True

            db.session.add(task)
            db.session.commit()
            flash('Update new status')


        if form.body.data:
            comment = Comment(task=task,
                              commentator=current_user._get_current_object(),
                              body=form.body.data)
            db.session.add(comment)
            db.session.commit()
            flash('The task has been commented.')


        return redirect(url_for('.task', id=task.id))

    return render_template('task.html', task=task, form=form, comments=comments, n_comments=n_comments)


@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    task = Task.query.get_or_404(id)

    if current_user != task.author:
        abort(403)
    form = TaskForm()
    if form.validate_on_submit():
        task.title = form.title.data
        task.body = form.body.data
        db.session.add(task)
        db.session.commit()

        flash('The task has been updated.')
        return redirect(url_for('.task', id=task.id))
    form.title.data = task.title
    form.body.data = task.body
    return render_template('edit_task.html', form=form)

flask_app/templates/_comments.html
<ul class="posts">
    {% for comment in comments %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=task.commentator.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ comment.author.gravatar(size=10) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(comment.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('.user', username=comment.commentator.username) }}">{{
                comment.commentator.username }}</a></div>
            <div class="post-body">
                <h4>{{ comment.body }}</h4>
            </div>

        </div>
    </li>
    {% endfor %}
</ul>

flask_app/templates/_macros.html
{% macro pagination_widget(pagination, endpoint) %}
<ul class="pagination">
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.prev_num, **kwargs) }}{% else %}#{% endif %}">
            &laquo;
        </a>
    </li>
    {% for p in pagination.iter_pages() %}
        {% if p %}
            {% if p == pagination.page %}
            <li class="active">
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% else %}
            <li>
                <a href="{{ url_for(endpoint, page = p, **kwargs) }}">{{ p }}</a>
            </li>
            {% endif %}
        {% else %}
        <li class="disabled"><a href="#">&hellip;</a></li>
        {% endif %}
    {% endfor %}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}>
        <a href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.next_num, **kwargs) }}{% else %}#{% endif %}">
            &raquo;
        </a>
    </li>
</ul>
{% endmacro %}

flask_app/templates/_tasks.html
<ul class="posts">
    {% for task in tasks %}

    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=task.author.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ task.author.gravatar(size=15) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(task.date_created).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('.user', username=task.author.username) }}">{{
                task.author.username }}</a></div>
            <div class="post-body">
                <a href="{{ url_for('.task', id=task.id) }}"><h4>{{ task.title }} ({{task.status}})</h4></a>
            </div>
            <div class="post-body">

                <h6>{{ task.body }}</h6>
            </div>
            <div class="post-footer">
                {% if current_user == task.author %}
                <a href="{{ url_for('.edit', id=task.id) }}">
                    <span class="label label-primary">Edit</span>
                </a>
                {% endif %}
                <!--                <a href="{{ url_for('.task', id=task.id) }}">-->
                <!--                    <span class="label label-default">Comment</span>-->
                <!--                </a>-->
            </div>
        </div>
    </li>

    {% endfor %}
</ul>

flask_app/templates/base.html
{% extends "bootstrap/base.html" %}
{% block title %}Flasky{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon1.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon1.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}

{% block navbar %}
<div class="navbar navbar-inverse" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}">Flasky</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('main.user', username=current_user.username) }}">Profile</a></li>
                {% endif %}
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ current_user.gravatar(size=18) }}">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ url_for('auth.change_password') }}">Change Password</a></li>
                        <li><a href="{{ url_for('auth.change_email_request') }}">Change Email</a></li>
                        <li><a href="{{ url_for('auth.logout') }}">Log Out</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{{ url_for('auth.login') }}">Log In</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ moment.include_moment() }}
{% endblock %}

flask_app/templates/edit_profile.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Profile{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Your Profile</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

flask_app/templates/edit_task.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Flasky - Edit Task{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Edit Task</h1>
</div>
<div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

flask_app/templates/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Flasky{% endblock %}

{% block page_content %}
<div class="page-header">
    <h3>Hello, {% if current_user.is_authenticated %}{{ current_user.username }}{% else %}Stranger{% endif %}!</h3>
</div>
<div>

    {% if current_user.is_authenticated %}
        <h4>Create new task:</h4>
        {{ wtf.quick_form(form) }}
            {% endif %}

</div>

{% include '_tasks.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.index') }}
</div>
{% endif %}
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

flask_app/templates/task.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}
{% import "_macros.html" as macros %}

{% block title %}Flasky - Task{% endblock %}

{% block page_content %}
<div>
    <h4>{{ task.title }}</h4>
    <div>
        <a href="{{ url_for('.user', username=task.author.username) }}">{{
            task.author.username }}
            <img class="img-rounded profile-thumbnail" src="{{ task.author.gravatar(size=20) }}">
        </a>
    </div>
    <br>
    <h6>{{ task.body }}</h6>
    <br>
    <p>Status: {{ task.status }}</p>
</div>

<div>
    {% if current_user.is_authenticated %}
    {{ wtf.quick_form(form) }}
    {% endif %}
</div>


<div>
    <h4>Comments: ({{ n_comments }})</h4>
</div>


<ul class="posts">
    {% for comment in comments %}
    <li class="post">
        <div class="post-thumbnail">
            <a href="{{ url_for('.user', username=comment.commentator.username) }}">
                <img class="img-rounded profile-thumbnail" src="{{ comment.commentator.gravatar(size=10) }}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{ moment(comment.timestamp).fromNow() }}</div>
            <div class="post-author"><a href="{{ url_for('.user', username=comment.commentator.username) }}">{{
                comment.commentator.username }}</a></div>
            <div class="post-body">
                <h6>{{ comment.body }}</h6>
            </div>

        </div>
    </li>
    {% endfor %}
</ul>


{% endblock %}

flask_app/templates/user.html
{% extends "base.html" %}

{% block title %}Flasky - {{ user.username }}{% endblock %}

{% block page_content %}
<div class="page-header">
    <img class="img-rounded profile-thumbnail" src="{{ user.gravatar(size=90) }}">
    <div class="profile-header">

        <h1>{{ user.username }}</h1>
        {% if user.name or user.location %}
        <p>
            {% if user.name %}{{ user.name }}{% endif %}
            {% if user.location %}
            From <a href="http://maps.google.com/?q={{ user.location }}">
            {{ user.location }}
        </a>
            {% endif %}
        </p>
        {% endif %}

        <p><a href="mailto:{{ user.email }}">{{ user.email }}</a></p>

        {% if user.about_me %}<p>{{ user.about_me }}</p>{% endif %}
        <p>
            Member since {{ moment(user.member_since).format('L') }}.
            Last seen {{ moment(user.last_seen).fromNow() }}.
        </p>
        <p>{{ user.tasks.count() }} tasks.</p>
        <p>
            {% if user == current_user %}
            <a class="btn btn-default" href="{{ url_for('.edit_profile') }}">Edit Profile</a>
            {% endif %}
        </p>
    </div>
</div>

<h3>Tasks by {{ user.username }}</h3>
{% include '_tasks.html' %}
{% if pagination %}
<div class="pagination">
    {{ macros.pagination_widget(pagination, '.user', username=user.username) }}
</div>
{% endif %}
{% endblock %}